### ISSUE TITLE
How can i send two data containers in single frame?

### ISSUE THREAD

**Issue by oczkers** [liris/websocket-client#144]
I've got only one day experience with websockets so sorry for my lack of knowledge.

I'm trying to build frame like browsers do ([wireshark](https://lh6.googleusercontent.com/-XRNMx5x_Dg8/VLmghBZ9nFI/AAAAAAAACKk/sAJQu-mWfmM/w1598-h999-no/two.png)) but sending continue frame followed by unfinished text ([wireshark](https://lh5.googleusercontent.com/-nEmtN6YsUs0/VLmghFNk0vI/AAAAAAAACKg/329FS6luYxw/w1598-h999-no/one.png)) just doesn't work - server is closing connection without any response.

**Comment by liris** [comment]
Please try the following...

```python
frame = ABNF("Hello," , fin=0, opcode=ABNF.OPCODE_TEXT)
ws.send_frame(frame)
frame = ABNF("World" , fin=1, opcode=ABNF.OPCODE_CONT)
```

**Comment by oczkers** [comment]
Thanks for reply.

[code]
ws = create_connection('ws://37.187.143.231:15990')
frame = ABNF.create_frame("Hello,", fin=0, opcode=ABNF.OPCODE_TEXT)
ws.send_frame(frame)
frame = ABNF.create_frame("World" , fin=1, opcode=ABNF.OPCODE_CONT)
ws.send_frame(frame)
[/code]
https://lh3.googleusercontent.com/-lP8UVgOf3xA/VNm8hq1c1iI/AAAAAAAACL4/_hHDdvUE5yc/w1598-h999-no/New%2BBitmap%2BImage_cr.png


Thats exactly what i tried but as You can see there are two frames sent separately but i need all data in only one frame like browsers do https://lh6.googleusercontent.com/-XRNMx5x_Dg8/VLmghBZ9nFI/AAAAAAAACKk/sAJQu-mWfmM/w1598-h999-no/two.png

**Comment by liris** [comment]
You want to call  "send "API twice and to send them in 1 frame.
We send data with no delay, so  we don't have any chance to pack them into 1 frame.

Please queque the "send" data and  pack them  into 1 frame by yourself.
