### ISSUE TITLE
PEP 440 package naming & versioning

### ISSUE THREAD

**Issue by jayvdb** [liris/websocket-client#147]
builds using this package report a warning for every release, including 0.23, and unreleased 0.24 looks like it will be no different

PEP440Warning: 'websocket (client-0.23.0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.

See e.g.

https://travis-ci.org/jayvdb/pywikibot-core/jobs/50130757

**Comment by invisibleroads** [comment]
The offending code seems to be in setuptools 8.2.1.
https://bitbucket.org/pypa/setuptools/issue/307/pep440-code-in-setuptools-821-is-parsing
The warning does not appear with setuptools 12.0.5.

**Comment by jayvdb** [comment]
If you look at lines 205 & 206 of the build log I linked to, it shows it **is** using setuptools 12.0.5
```
205 $ python -c "import setuptools; print(setuptools.__version__)"
206 12.0.5
```

(we've had setuptools version problems before, which is why we have that debugging in our travis builds)

**Comment by invisibleroads** [comment]
Hmm, that is true.  I didn't see the warnings because I didn't have the logger configured.

Hopefully, setuptools will fix it soon because there are a lot of packages with hyphenated names.

**Comment by liris** [comment]
Thank you for your report.
We don't get this warning in setuptool 12.0.5, so I close this issue.

**Comment by jayvdb** [comment]
Why is this closed.  It does happen with 12.0.5, as shown above.

**Comment by liris** [comment]
I didn't get this warning in setuptools 12.2.

**Comment by jayvdb** [comment]
I am still seeing it with setuptools 14.0 and "websocket (client-0.25.0)"

invisibleroads/socketIO-client#66 solved the same problem by replacing '-' with '_' in setup.
