### ISSUE TITLE
How to get response header after websocket connection established?

### ISSUE THREAD

**Issue by RicterZ** [liris/websocket-client#160]
I try to find a way to get response header, but the WebSocket class doesn't provide a method or attribute to get it.

**Comment by liris** [comment]
Our library doesn't provide such a method.
Why do we need it?

**Comment by RicterZ** [comment]
Sometimes other programs need the status code and the response headers in the context I think.
And in fact I met the problem so I have to fork it and change some code, it's very inconvenient.
