### ISSUE TITLE
_http.py _ssl_socket function is F'd-up

### ISSUE THREAD

**Issue by enewhuis** [liris/websocket-client#167]
The sslopt argument is shadowed by a local variable and a later line of code thinks that it is not.  The result is that none of the sslopt provided by the user are used.

def _ssl_socket(sock, sslopt, hostname):
    sslopt = dict(cert_reqs=ssl.CERT_REQUIRED)
    certPath = os.path.join(
        os.path.dirname(__file__), "cacert.pem")
    if os.path.isfile(certPath):
        sslopt['ca_certs'] = certPath
    sslopt.update(sslopt)
    check_hostname = sslopt.pop('check_hostname', True)
    sock = ssl.wrap_socket(sock, **sslopt)
    if (sslopt["cert_reqs"] != ssl.CERT_NONE and check_hostname):
        match_hostname(sock.getpeercert(), hostname)

**Comment by liris** [comment]
sorry.
fixed with your PR #168

**Comment by enewhuis** [comment]
I think ca_certs also needs to be set to None or else cert_reqs is overridden in the ssl.py
