### ISSUE TITLE
wsdump doesn't work with piped input

### ISSUE THREAD

**Issue by sim6** [liris/websocket-client#183]
Firstly thanks for your work.

Please could you improve wsdump to work with piped input.

Thanks again.

```shell
echo "hi!" | wsdump ws://echo.websocket.org
```
```shell
Traceback (most recent call last):
  File "/usr/bin/wsdump", line 16, in <module>
    ENCODING = getattr(sys.stdin, "encoding", "").lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by sim6** [comment]
Thanks! I'm fine with encoding issue, but not sure about EOF issue. Anyway, please, take a look at https://github.com/liris/websocket-client/pull/184

**Comment by sim6** [comment]
If the reply of server is too slow, then it is not processed because the EOF. But you can wait before send the EOF.
```
$ echo "hi!" | ./wsdump.py ws://echo.websocket.org
Press Ctrl+C to quit
> > 
$ { echo "hi!"; sleep 1; } | ./wsdump.py ws://echo.websocket.org
Press Ctrl+C to quit
< hi!
> 
```

**Comment by liris** [comment]
I added a command line argument, "--eof-wait".
If you set this, wsdump.py will wait for the specified period(second) after received EOF.

**Comment by budkin** [comment]
The issue is still there
```
$ wsdump.py ws://localhost:3001/staff -v -s binary --eof-wait 10
'NoneType' object has no attribute 'lower'
```

Any ideas?
