### ISSUE TITLE
[Support] How to add HTTP headers

### ISSUE THREAD

**Issue by JonathanHuot** [liris/websocket-client#191]
Is it possible to add custom HTTP headers ? It is required to tweak HTTP Host, and also to add custom HTTP Cookie which include authentification to Websocket server.

It will be very useful, and I'm sure adding only a "headers" dict to the connection/WebSocket object will ne enough.

Thanks for your very nice project.

**Comment by liris** [comment]
Please write like the following...

```python
import webscocket

conn  = websocket.create_connection("ws://echo.webscoket.org/",
    header=["User-Agent: MyProgram", "x-custom: my-custom-header"],
    cookie="some cookie value")
```
