### ISSUE TITLE
How to Verify Message Has Left the Buffer

### ISSUE THREAD

**Issue by Biolutions** [liris/websocket-client#192]
Hello liris,

I'm having an issue confirming that all of my messages have been sent to the websocket server when calling the send command very quickly followed by a close() command. When I do this some fraction of my messages are never sent to the server because the connection is closed as soon as the close() command is executed. 

From my understanding of websockets the send(msg) command should add msg to a buffer that will at some point be sent. After reading your documentation I am still unsure how to access the buffer size. I would like to be able to do this so that I can verify it is empty before I close the connection and also to make sure there is never more than 1 message waiting to be sent. 

Other API's I have seen on the internet define methods to access the size of the buffer currently storing all of the messages, thus allowing you to make sure every message is sent before closing the connection. Have you implemented something similar to this that I just haven't been able to find yet? 

Thanks!

**Comment by liris** [comment]
We don't store any sending message on a buffer. The message will immediately be sent when we call "send" method.

If you are using on the multi thread, the thread context might be switched. Can I have a source code to verify this?

**Comment by Biolutions** [comment]
Sorry for the late reply liris. We are using node.js to host our websocket echo server. Below is the python code and the websocket.js code. When I run this the websocket server reports receiving around half of the messages that were supposed to be sent. This can be fixed by un -commenting the recv command but the rate the messages are sent at takes a significant hit. 

<b>Python</b>

    import websocket
    import time

    def connect():
        print "Establishing connection"
        ws = websocket.create_connection("ws://16.78.182.166:8080", subprotocols=["echo-protocol"])
        num_messages = 100000

        start = time.time()
        for i in range(0, num_messages):
            ws.send("Hello World")
            #ws.recv()
        ws.close()
        end = time.time()
        print "Rate", (num_messages/(end - start))

       if __name__ == '__main__':
           connect()


<b>Node.js</b>

    #!/usr/bin/env node
    var WebSocketServer = require('websocket').server;
    var http = require('http');

    var server = http.createServer(function(request, response) {
        console.log((new Date()) + ' Received request for ' + request.url);
        response.writeHead(404);
        response.end();
    });
    server.listen(8080, function() {
        console.log((new Date()) + ' Server is listening on port 8080');
    });

    wsServer = new WebSocketServer({
        httpServer: server,
        autoAcceptConnections: false
    });

    function originIsAllowed(origin) {
      // put logic here to detect whether the specified origin is allowed.
      return true;
    }

    wsServer.on('request', function(request) {
        var numMessages = 0;
        if (!originIsAllowed(request.origin)) {
          // Make sure we only accept requests from an allowed origin
          request.reject();
          console.log((new Date()) + ' Connection from origin ' + request.origin + ' rejected.');
          return;
        }

        var connection = request.accept('echo-protocol', request.origin);
        console.log((new Date()) + ' Connection accepted.');
        connection.on('message', function(message) {
            if (message.type === 'utf8') {
                console.log('Received Message: ' + message.utf8Data);
	        numMessages++;
                connection.sendUTF("ok");
            }
            else if (message.type === 'binary') {
                console.log('Received Binary Message of ' + message.binaryData.length + ' bytes');
                //connection.sendBytes(message.binaryData);
           }
        });
        connection.on('close', function(reasonCode, description) {
	    console.log('NumMessages: ' + numMessages);
            console.log((new Date()) + ' Peer ' + connection.remoteAddress + ' disconnected.');
        });
    });

**Comment by liris** [comment]
close timeout was 3 sec and if we cannot send data within 3sec, the buffered data is lost.

now, we can set timeout on close method, please set None for timeout.

```python
ws.close(timeout=None)
```

But if the server doesn't send close frame, we will wait forever and program will be hang up.

```python
ws.close(timeout=10)
```
In this case, program will wait 10 sec as max.

**Comment by Biolutions** [comment]
Thank you for the fix. Just so I am clear on the issue, this still doesn't allow me to monitor the buffer or number of messages sent? The timeout=None will make it so messages are no longer dropped but if I wanted to implement a rate controller or sent message counter on the client side there is no guarantee they will be accurate. They can only count when a message is placed in the buffer and know that it will be sent but not when?

**Comment by SinaRanjkeshzade** [comment]
Hi,
I have similar problem, I use "websocket.send()" in python to send about 1024 bytes every 100 mili-seconds and after a while, "websocket.send()" makes an exception (gives error). As I read in tutorial, it will happen whenever buffer is full. But I don't know how to solve this problem. 
In my code I've used "await websocket.send()" inside a loop.run_until_complete and this is my error 

`File "<ipython-input-1-2de4519b4e62>", line 144, in service_connection await ws.send(message) File "Local_Addr\lib\site-packages\websockets\protocol.py", line 530, in send await self.ensure_open() File "Local_Addr\lib\site-packages\websockets\protocol.py", line 779, in ensure_open await asyncio.shield(self.close_connection_task) File "Local_Addr\lib\asyncio\futures.py", line 260, in __await__ yield self # This tells Task to wait for completion`

I'm really in hurry and any help will be appreciated.

**Comment by engn33r** [comment]
SinaRanjkeshzade this is an old issue, but it looks like you are using the `websockets` package, not the `websocket-client` package, so you can ask your question to the other project
