### ISSUE TITLE
How to check type of response message?

### ISSUE THREAD

**Issue by rasmi** [liris/websocket-client#198]
I'm dealing with an API that returns both JSON and binary responses. I'd like to perform different actions depending on the type of response returned. Is there an obvious way to check this through the library (i.e. does the response message have some code or property I can check that describes the payload type?), or should I just inspect the responses myself for key features and decide what to do based on that?

**Comment by liris** [comment]
Please use recv_data instead of recv.

recv_data will return opcode and data payload.

**Comment by rasmi** [comment]
Is there any way to do this with the WebSocketApp approach? Right now I'm handling responses using `on_message` callback. I can do it the other way if WebSocketApp doesn't support this.

**Comment by liris** [comment]
Please use on_data callback.

```python
on_data(app, data, opcode, fin):
    if opcde == ABNF.OPCODE_BINARY:
        pass # do something...
```
