### ISSUE TITLE
How to get error status code?

### ISSUE THREAD

**Issue by embach** [liris/websocket-client#199]
Currently the error exception returns two parameters on_error(ws, error) and if the http status is needed I have to parse the error text: raise WebSocketException("Handshake Status %d" % status).
How could I find out the status code without parsing the composed text each time. Maybe be a third param on_error(ws, error, status) would be useful? The point here is, that a micro controller e.g. raspi should automatically reconnect, if a error occurs, excepting if the error status is 401 (Not authorized) no reconnect is needed.
Thank You in advance!

**Comment by liris** [comment]
WebSocketBadStatusException will be raised and you can get the status code.

```python
on_error(app, error):
  if isinstance(error, WebSocketBadStatusException):
    status = error.status_code
```

**Comment by embach** [comment]
Just tested, worked perfectly. Thanx!
