### ISSUE TITLE
Client certificates do not work with 2.7.9+ and 3.2+

### ISSUE THREAD

**Issue by robviaas** [liris/websocket-client#207]
Because a new SSLContext is created within _wrap_sni_socket(), we do not have the option to pass in the certfile and keyfile values (or have them already set in a context). As such, SSL client certificates do not work with websocket-client.

**Comment by robviaas** [comment]
To reproduce the issue, create a self-signed root certificate and issue a client cert from that root certificate. Good instructions for creating these at https://help.github.com/enterprise/11.10.340/admin/articles/using-self-signed-ssl-certificates/
Make certain to set the Common Name (CN) value to something relevant (we skip the hostname check in the test so it doesn't matter what you choose, just that it is something). In addition, you may need to create a PEM file with key & cert for the server. These are just concatenated together, as in:
cat rootCA.key rootCA.crt > rootCA.pem

On the server side, require the certificate. Here's an example from a haproxy config (nginx and other web servers are similar):
bind 127.0.0.1:443 ssl crt /tmp/test_keys/rootCA.pem ca-file /tmp/test_keys/rootCA.crt verify required 

Reference all three relevant files in the sslopt argument:
import websocket
sslopt = {
  'check_hostname': False,
  'keyfile': '/tmp/test_keys/host.key',
  'certfile': '/tmp/test_keys/host.crt',
  'ca_certs': '/tmp/test_keys/rootCA.crt',
}
url = 'wss://127.0.0.1/echo/'
websocket.create_connection(url, sslopt=sslopt)

A failure shows some sort of SSL error like:
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)

**Comment by liris** [comment]
I've merge PR.
