### ISSUE TITLE
Use os.urandom() for cryptographically-secure random bytes

### ISSUE THREAD

**Issue by obi1kenobi** [liris/websocket-client#210]
The creation of a websocket 16-byte nonce for the initial handshake is done through a `uuid.uuid4()` call, which is not intended for generating unpredictable bytes for security or crypto purposes. Please use `os.urandom()` with 16 bytes of random data, because it is explicitly intended for such use.

**Comment by liris** [comment]
I've merged PR

**Comment by obi1kenobi** [comment]
Thank you!
