### ISSUE TITLE
WebSocketPayLoadException

### ISSUE THREAD

**Issue by hp685** [liris/websocket-client#216]
File "/usr/local/lib/python2.7/site-packages/websocket_client-0.21.0-py2.7.egg/websocket/_core.py", line 667, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python2.7/site-packages/websocket_client-0.21.0-py2.7.egg/websocket/_core.py", line 684, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python2.7/site-packages/websocket_client-0.21.0-py2.7.egg/websocket/_core.py", line 723, in recv_data_frame
    raise WebSocketPayloadException("cannot decode: " + repr(frame.data))
websocket._exceptions.WebSocketPayloadException: cannot decode: '\x81~\x01\x05'

I'm using websocket-client in my application and upon doing a recv(), I get this error. Is there an option that will make the web socket handle binary data as well?

**Comment by liris** [comment]
Is it "BINARY" frame. I think server sent binary data as "TEXT" frame.

**Comment by hp685** [comment]
I can't tell for sure that its the server that garbles the data-- I have javascript based socket clients that use the same server and the browser seems to render it correctly every-time, while when I use websocket-client to access the same data, it does so correctly most times (29/30), but about once in a while, I encounter frame corruption and this exception gets raised.

**Comment by hp685** [comment]
Upon packet sniffing, it appears that the server is sending corrupt frames. Closing this issue.
