### ISSUE TITLE
"next" method to unlock "recv" loop (blender single thread)

### ISSUE THREAD

**Issue by ivopc** [liris/websocket-client#234]
I am working in a script that can only run in a single thread and is doing an infinite loop, the single thread is a blender game engine limitation (I can't use async or anything multithread-like). The .recv() method is freezing the game interface to get the server response. 
Here a very dangerous "kludge" example to solve the loop freezing in blender (this run in a infinite loop):

```
data = ws.recv()

print(data)

if data == "walk":
    walk()

if data == "jump":
    jump()
    
ws.send("unlock_thread") // a "ws.nextFrame()" or "ws.unlock()" like
```

And the server consists to callback a message to client when it send a message to unlock the game interface, like that:

```
connection.on("message", function (message) { 
	connection.send("unlocking thread")
})
```
But this solution is very dangerous and kludge considering the client connection speed and server perfomance.

Thanks.

**Comment by liris** [comment]
We have to run event loop somewhere. it looks no way to run this library on blender's single thread.

**Comment by ivopc** [comment]
Really? There's no way to run event loop in blender?

**Comment by ivopc** [comment]
Really? There's no way to run event loop in blender? (Without blocking the blender thread)
Something that simply ignore if there is not response from the server

**Comment by ivopc** [comment]
And I really don't how that works in **_core.py**:

```
        self.frame_buffer = frame_buffer(self._recv, skip_utf8_validation)
        self.cont_frame = continuous_frame(fire_cont_frame, skip_utf8_validation)
```


How **.send()** "unlock" the .**recv()** method?

**Comment by ivopc** [comment]
There's no way to simulate a server message to client in the client?

**Comment by ivopc** [comment]
I have found a solution that is consists creating a internal server in client computer parallel to the blender process (game client). The client connect to the internal server and make the socket.recv loop. If the internal server (with asyncio) don't receive response from external server, simply send an empty message to the client (releasing the blender thread).

Sending data:
Client -> internal server (local server) -> external server (game server)

Receiving data:
client request to the internal server -> internal server check if have response from the external server: 
if don't: return null message to unlock blender thread
if have: return the data

And that release the blender thread (and "simulate" an async/multi thread client)...

If there wasn't this internal server would have much lag and a lot of problems about external server perfomance.
