### ISSUE TITLE
setsockopt

### ISSUE THREAD

**Issue by giantsrg1** [liris/websocket-client#263]
I am copying the code you have set up:

ws.run_forever(sockopt=((socket.IPPROTO_TCP, socket.TCP_NODELAY),))

and i am getting this error...

setsockopt() takes exactly 3 arguments (2 given)

**Comment by liris** [comment]
you should set sockopt like this.

  ws.run_forever(sockopt=((socket.IPPROTO_TCP, socket.TCP_NODELAY, 1),))
