### ISSUE TITLE
on_close handler doesn't work with class method and close event value / reason

### ISSUE THREAD

**Issue by jbwdevries** [liris/websocket-client#268]
For example, this works:

    class WebSocketClient(object):
        def __init__(self):
            self.application = websocket.WebSocketApp(on_close=self.on_close)

        def on_close(self, ws):
            pass

However, if you want the close event value and reason, according to _app.py you have to add two arguments:

    class WebSocketClient(object):
        def on_close(self, ws, code, reason):
            pass

But this doesn't work since the inspect there sees 4 arguments:

    on_close() takes exactly 4 arguments (2 given)

If you add only one, it does try to add both arguments, but then it won't work:

    on_close() takes exactly 3 arguments (4 given)

Not sure how to fix it. You can check if it's a method pretty easily via `hasattr(self.on_close, 'im_class')`. But that wouldn't fix it for partials I guess. Maybe the easiest way is to do instead of `!= 3`, `>= 3`.

I can work around it. Just putting it out here for future reference.

**Comment by liris** [comment]
you should define "def on_close(self, code, reason)"
