### ISSUE TITLE
Opcode error while sending data through python3

### ISSUE THREAD

**Issue by sacOO7** [liris/websocket-client#284]
send: b'\x81\xbe\x90\xedA\xe3\xeb\xcf"\x8a\xf4\xcf{\xc3\xa1\xc1a\xc1\xf4\x8c5\x82\xb2\xd7a\x98\xb2\x8c4\x97\xf8\xb9.\x88\xf5\x83c\xd9\xb0\x834\x8f\xfc\x90m\xc3\xb2\x887\x86\xfe\x99c\xd9\xb0\xcfb\x8b\xf1\x83%\x90\xf8\x8c*\x86\xb2\x90'
name 'opcode' is not defined

**Comment by willmcgugan** [comment]
I think that may be fixed in https://github.com/liris/websocket-client/pull/285
