### ISSUE TITLE
Setting Ping Message : Please advice

### ISSUE THREAD

**Issue by srini-murthy** [liris/websocket-client#78]
Dear Author,

Is there a way I can send "IAM ALIVE" message regularly along with ping.  My aim is to send heartbeat to the server that my application is alive.

Also, as per your advice, I set the following code.

ws.run_forver( ping_interval=30, ping_timeout=10) This goes to On_error after sending the first message and When I unplug the network cable this still does not raise error after 10 seconds as set by timeout.

Look forward to your advice.

Thank you sir.

BRE

**Comment by mkonecny** [comment]
> This goes to On_error after sending the first message 

This sounds like it's related to my bug (#237). Ping interval is every 30 seconds, but it raises and error because in the code 30 > 10.
